### ISSUE TITLE
can't modify the log-error path

### ISSUE THREAD

**Issue by gdnico** [edestecd/puppet-mariadb#34]
Hello,

I would like to send the log error in an other directory that /var/lib/mysql. But i can't change the value

Regards
Nicolas

**Comment by thaylin** [comment]
Have you tried adding it to override_options? such as :

override_options  => {
    'log-error' =>  '/var/log/mariadb/mariadb.log',
}

**Comment by gdnico** [comment]
Hi 
That's work
You can close the issue.
Thank you

**Comment by gdnico** [comment]
Hello,

I try it. That’s work.

Do you have an example of a cluster secure with ssl ?


Thank you



[signature_449231823]

Nicolas DOLE
Enterprise Architect

ndole@idgroup.com<mailto:ndole@idgroup.com>
+33 3 59 63 56 97


162 boulevard de fourmies bp 615
59061 Roubaix Cedex 1


PLEASE CONSIDER THE ENVIRONMENT BEFORE PRINTING !

This e-mail contains confidential informations. They are intended only to the person or the company whose name is mentioned. If you are not the intended recipient, please advise the sender immediately and delete the original e-mail from your own system. Any disclosure and reproduction on the contents of this email is strictly prohibited.

De : thaylin <notifications@github.com>
Répondre à : edestecd/puppet-mariadb <reply@reply.github.com>
Date : samedi 20 octobre 2018 à 14:32
À : edestecd/puppet-mariadb <puppet-mariadb@noreply.github.com>
Cc : DOLE Nicolas <NDOLE@idgroup.com>, Author <author@noreply.github.com>
Objet : Re: [edestecd/puppet-mariadb] can't modify the log-error path (#34)


Have you tried adding it to override_options? such as :

override_options => {
'log-error' => '/var/log/mariadb/mariadb.log',
}

**Comment by gdnico** [comment]
Hello,

Do you have an example how to create a user and db with yaml ?

Regards



[signature_1346144946]

Nicolas DOLE
Enterprise Architect

ndole@idgroup.com<mailto:ndole@idgroup.com>
+33 3 59 63 56 97


162 boulevard de fourmies bp 615
59061 Roubaix Cedex 1


PLEASE CONSIDER THE ENVIRONMENT BEFORE PRINTING !

This e-mail contains confidential informations. They are intended only to the person or the company whose name is mentioned. If you are not the intended recipient, please advise the sender immediately and delete the original e-mail from your own system. Any disclosure and reproduction on the contents of this email is strictly prohibited.

De : thaylin <notifications@github.com>
Répondre à : edestecd/puppet-mariadb <reply@reply.github.com>
Date : samedi 20 octobre 2018 à 14:32
À : edestecd/puppet-mariadb <puppet-mariadb@noreply.github.com>
Cc : DOLE Nicolas <NDOLE@idgroup.com>, Author <author@noreply.github.com>
Objet : Re: [edestecd/puppet-mariadb] can't modify the log-error path (#34)


Have you tried adding it to override_options? such as :

override_options => {
'log-error' => '/var/log/mariadb/mariadb.log',
}

**Comment by thaylin** [comment]
override_options => {
    client => {
      'socket'  =>  '/var/run/mysql/mysql.sock',
    },
    mysqld => {
      'bind-address'  =>  '0.0.0.0',
      'datadir' => '/mysql_data',
      'pid-file'  => '/var/run/mysql/mysql.pid',
      'socket'  => '/var/run/mysql/mysql.sock',
      'innodb_log_file_size'  => '4G',
      'max_allowed_packet'  => '1G',
      'character-set-server'  =>  'utf8',
      'collation-server'  => 'utf8_bin',
      'general_log' => 'on',
      'general_log_file' => '/var/log/mariadb/query.log',
      'log-error' =>  '/var/log/mariadb/mariadb.log',
      'open-files-limit'  => '500000',
      'max_connection'  => '1000',
      'innodb_buffer_pool_size'  =>  '8589934592',
      'innodb_flush_method' =>  'O_DSYNC',
      'ssl-ca'  =>  '/etc/mysql-ssl/ca-cert.pem',
      'ssl-cert'  =>  '/etc/mysql-ssl/server-cert.pem',
      'ssl-key' =>  '/etc/mysql-ssl/server-key.pem',
    },"

it is really just taking hash key=>value pairs and putting them in there...

As for the yaml, that is listed on the main page:

mariadb::cluster::override_options:
  mysqld:
    performance_schema: OFF
    innodb_file_per_table: OFF

So you could take the above for instance and do:

mariadb::cluster::override_options:
  mysqld:
    performance_schema: OFF
    innodb_file_per_table: OFF
    ssl-ca: '/etc/mysql-ssl/ca-cert.pem'
    ssl-cert: '/etc/mysql-ssl/server-cert.pem'
    ssl-key:  '/etc/mysql-ssl/server-key.pem'

I have not tested the yaml portion yet.

**Comment by edestecd** [comment]
@gdnico are you doing a cluster or just server?
I can get you one of our profiles if you like, which sets up ssl for the cluster or stand alone server. Which do you want?

**Comment by gdnico** [comment]
Hello,

I do a ssl cluster. I find the correct syntax.

My last problem is to create an user and a database with yaml.


Thank you



[signature_1636300524]

Nicolas DOLE
Enterprise Architect

ndole@idgroup.com<mailto:ndole@idgroup.com>
+33 3 59 63 56 97


162 boulevard de fourmies bp 615
59061 Roubaix Cedex 1


PLEASE CONSIDER THE ENVIRONMENT BEFORE PRINTING !

This e-mail contains confidential informations. They are intended only to the person or the company whose name is mentioned. If you are not the intended recipient, please advise the sender immediately and delete the original e-mail from your own system. Any disclosure and reproduction on the contents of this email is strictly prohibited.

De : Chris Edester <notifications@github.com>
Répondre à : edestecd/puppet-mariadb <reply@reply.github.com>
Date : mardi 23 octobre 2018 à 14:18
À : edestecd/puppet-mariadb <puppet-mariadb@noreply.github.com>
Cc : DOLE Nicolas <NDOLE@idgroup.com>, Mention <mention@noreply.github.com>
Objet : Re: [edestecd/puppet-mariadb] can't modify the log-error path (#34)


@gdnico<https://github.com/gdnico> are you doing a cluster or just server?
I can get you one of our profiles if you like, which sets up ssl for the cluster or stand alone server. Which do you want?
