### ISSUE TITLE
dependancy cycle

### ISSUE THREAD

**Issue by thaylin** [edestecd/puppet-mariadb#35]
When I try to install a server I get the error:

(File[/etc/locale.conf] => Class[Locales] => Stage[setup] => Stage[main] => Class[Mariadb::Repo::Yum] => Yumrepo[mariadb] => Package[glibc-common] => File[/etc/locale.conf])

The error happens no matter how I attemtp to use it 

include mariadb::server

class { 'mariadb::server':
options
}

I am on rhel 7.5 with puppet 4.10. I have the mysql and its dependencies loaded into the puppet file. I cannot see any requirements for locales in the code, but this is a new error for me.

**Comment by edestecd** [comment]
what version of the module are you using?

**Comment by edestecd** [comment]
what is managing locals and glibc-common?

**Comment by thaylin** [comment]
mod 'saz-locales', '2.3.0'

**Comment by thaylin** [comment]
as for what version of your module I am using, I am using your latest.

**Comment by edestecd** [comment]
were using 1.1.1 without issue, so i suspect an issue with that locals module or some ordering you have in a role or profile.

**Comment by edestecd** [comment]
re open if you are still having this issue
