### ISSUE TITLE
mysql::deepmerge is deprecated

### ISSUE THREAD

**Issue by minorOffense** [edestecd/puppet-mariadb#38]
The 8.0.0 mysql puppet module deprecated the deepmerge function.

**Comment by edestecd** [comment]
DO you know what the alternative is?

**Comment by minorOffense** [comment]
Haven't looked into it yet (I was gonna open a PR for it). I just tried using the 8.0.0 version, saw the error message and then saw the changelog for that version.

https://forge.puppet.com/puppetlabs/mysql/changelog#changed

The release came out like a week or two ago.

**Comment by minorOffense** [comment]
Looking at the mysql module, I think the deep merge is just a function on hashes now if you include puppet-stdlib

See https://github.com/puppetlabs/puppetlabs-mysql/blob/master/manifests/server.pp#L119

**Comment by minorOffense** [comment]
Aaaand looks like they undid the change: https://github.com/puppetlabs/puppetlabs-mysql/pull/1181

**Comment by edestecd** [comment]
Seems ok now, reoopen if necessary
