### ISSUE TITLE
Unable to resolve all dependencies due to out of date <5.0 stdlib

### ISSUE THREAD

**Issue by ragingdave** [edestecd/puppet-mariadb#42]
I found and maybe others have as well, that the dependency of <5.0.0 on puppetlabs-stdlib ends up making resolving dependencies across this and other packages near impossible. Is there any reason not to be able to use stlib > 5? I'm basically running into a huge road block as a result of this incompatibility

**Comment by edestecd** [comment]
Not that I can think of. I'll merge a PR that fixes this

**Comment by edestecd** [comment]
This should be fixed with the latest version @ragingdave
