### ISSUE TITLE
percona Keyserver not using correct signature:

### ISSUE THREAD

**Issue by we-CONECT-Joe** [edestecd/puppet-mariadb#5]
Err:5 http://repo.percona.com/apt xenial InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 9334A25F8507EFA5
Get:9 http://us.archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]
Get:10 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Reading package lists... Done
W: GPG error: http://repo.percona.com/apt xenial InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 9334A25F8507EFA5

**Comment by edestecd** [comment]
It is possible that they changed the key.

**Comment by edestecd** [comment]
This is useful:
https://www.percona.com/blog/2016/10/13/new-signing-key-for-percona-debian-and-ubuntu-packages/

We need to update this code:
https://github.com/edestecd/puppet-mariadb/blob/master/manifests/repo/percona/apt.pp

**Comment by edestecd** [comment]
Basically we need an if just like we have here in the main repo:
https://github.com/edestecd/puppet-mariadb/blob/master/manifests/repo/apt.pp#L10

The new key is for xenial (16.04) and up only.

**Comment by edestecd** [comment]
Here is the new key fingerprint (id):  4D1B B29D 63D9 8E42 2B21  13B1 9334 A25F 8507 EFA5

```puppet
  if (($::operatingsystem == 'Debian') and (versioncmp($::operatingsystemrelease, '8.0') >= 0)) or
  (($::operatingsystem == 'Ubuntu') and (versioncmp($::operatingsystemrelease, '16.04') >= 0)) {
    $key = {
      'id' => '4D1BB29D63D98E422B2113B19334A25F8507EFA5',
    }
  } else {
    $key = {
      'id' => '430BDF5C56E7C94E848EE60C1C4CBDCDCD2EFD2A',
    }
  }
```

**Comment by edestecd** [comment]
Would you like to make a PR for this?

**Comment by we-CONECT-Joe** [comment]
wow great support! Thank you very much!

i will fork you now and apply the patch.

**Comment by we-CONECT-Joe** [comment]
pull request sent =)

thanks again!
