### ISSUE TITLE
Why does the cluster_peers example start with "delete" ?

### ISSUE THREAD

**Issue by we-CONECT-Joe** [edestecd/puppet-mariadb#7]
` wsrep_cluster_peers     => delete(['192.168.1.1', '192.168.1.2', '192.168.1.3'], $::ipaddress)`

in most other galera modules, peers are defined without the delete:
`   galera_servers => ['192.168.171.1', '192.168.171.2', '192.168.171.3'],`

im not complaining, i am just curious

**Comment by edestecd** [comment]
It is possible that galera handles this gracefully. In other words it excludes the nodes ip from the list...
This peer list is used to determine who to sync with on initial boot. It will try each in the list until it finds a good candidate. It's probably not good to sync with yourself, so I always exclude each hosts own ip.

Maybe galera is smart enough to do this for you, but I feel safer doing so. Its an example, so anyone is free to disagree with me...

**Comment by we-CONECT-Joe** [comment]
great. Makes total sense!

should be in the readme though :D

**Comment by edestecd** [comment]
Feel free to add something to the README about this...

**Comment by we-CONECT-Joe** [comment]
so just as a sidenote, you are not going to invest anymore time in this?
so far i seem to be the "only" cobtributor that came along, are you planning on maintaining this at any point?

I Mean the Mariadb install is nice and easy to handle but it seems to me the fork is making more sense and just abstracting anything myself rather than pushing it upstream is an option.
You can just pull from my repo the sameway i pull from  yours. and since im using puppet librarian im using git repos for everything else anyways.

**Comment by edestecd** [comment]
I am planning on maintaining this module and publishing new releases to the forge.
I simply meant that I would like you to make another PR, for the additional README content.

I'm fixing the spec tests now so that you can rebase your other PRs and we can get them merged ;)

**Comment by edestecd** [comment]
Using git repos is also a good option. I have had puppet instructors recommend pulling all your modules from repos with R10k etc...

That being said, I would appreciate your contributions and it would be nice if we could work together on a single code base rather than forking our separate ways...
